background = 0xDFF1EDE8 # background color
base = 0xDFD5BDAE # Top Bar
text = 0xFF452C22
alternate_base = 0xFF5D413F # outline
bright_text = 0xFFFDEDED
accent = 0xFF8A116E
accent_secondary = 0xFFCB6EED
h1_size = 19
h2_size = 15
h3_size = 13
font_size = 11
small_font_size = 10
icon_theme = empty
font_family = "Fira Code"
font_family_monospace = monospace
rounding_large = 10
rounding_small = 5
